#!/usr/bin/env bash
#Terminates the "infinity and beyond" program using the SIGKILL signal.

#Obtains the PID (Process ID) of the program.
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
