#!/usr/bin/env bash
# Displays the phrase "infinity and beyond" indefinitely unless stopped,
#humorously noting that it's not truly eternal if it can be terminated.

#Manages the SIGTERM signal.
trap "echo 'I am invincible!!!'" 15


# print the message forever
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
